apiVersion: v1
kind: Template
metadata:
  name: ninja-board-back-end
  annotations:
    iconClass: icon-jboss
    tags: quarkus, java
    description: Build the back-end Ninja Board App
labels:
  application: ${APPLICATION_NAME}
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ubi-quarkus-native-s2i
  spec:
    tags:
    - from:
        kind: DockerImage
        name: quay.io/quarkus/ubi-quarkus-native-s2i:20.1.0-java11
      name: 20.1.0-java11
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-build
  spec:
    tags:
    - from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi8-minimal
      name: latest
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ubi-minimal
  spec:
    tags:
    - from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi8-minimal
      name: latest
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${SECRET_REF}
  stringData:
    WebHookSecretKey: ${WEBHOOK_SECRET_KEY}
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    lookupPolicy:
      local: false
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
      app.kubernetes.io/component: ${APPLICATION_NAME}
      app.kubernetes.io/instance: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-build
  spec:
    resources:
      limits:
        memory: 1Gi
        cpu: '1'
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}-build:latest
    source:
      contextDir: ${SOURCE_REPOSITORY_DIR}
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: ARTIFACT_DIR
          value: "all-service/target"
        - name: ARTIFACT_COPY_ARGS
          value: "-p -r lib/ *-runner.jar"
        from:
          kind: ImageStreamTag
          name: ubi-quarkus-native-s2i:20.1.0-java11
      type: Source
    triggers:
    - type: ConfigChange
    - imageChange:
      type: ImageChange
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    source:
      contextDir: ${SOURCE_REPOSITORY_DIR}
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      sourceStrategy:
        env:
          - name: ARTIFACT_DIR
            value: "all-service/target"
          - name: ARTIFACT_COPY_ARGS
            value: "-p -r lib/ *-runner.jar"
          - name: USERS_LDAP_PROVIDER
            value: ${USERS_LDAP_PROVIDER}
          - name: USERS_LDAP_BASEDN
            value: ${USERS_LDAP_BASEDN}
        from:
          kind: ImageStreamTag
          name: ubi-quarkus-native-s2i:20.1.0-java11
      type: Source
    triggers:
    - type: GitHub
      github:
        secretReference:
          name: ${SECRET_REF}
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    strategy:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}
          deploymentconfig: ${APPLICATION_NAME}
      spec:
        containers:
        - image: ${APPLICATION_NAME}:latest
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: 8778
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
  status:
    loadBalancer: {}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${APPLICATION_NAME}
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ${APPLICATION_NAME}
parameters:
  - name: APPLICATION_NAME
    description: The name for the application.
    required: true
    value: ninja-board-back-end
  - name: SOURCE_REPOSITORY_URL
    description: The source URL for the application
    displayName: Source URL
    value: https://github.com/redhat-cop/ninja-board
    required: true
  - name: SOURCE_REPOSITORY_REF
    description: The branch name for the application
    displayName: Source Branch
    value: v2
    required: true
  - name: SOURCE_REPOSITORY_DIR
    description: The location within the source repo of the application
    displayName: Source Directory
    value: quarkus
    required: true
  - name: USERS_LDAP_BASEDN
    description: Ldap basedn
    required: true
    value: ou=users,dc=redhat,dc=com
  - name: USERS_LDAP_PROVIDER
    description: Ldap provider
    required: true
    value: ldap://ldap.corp.redhat.com:389
  - name: SECRET_REF
    description: The secret reference
    required: true
    value: backend-secret
  - name: WEBHOOK_SECRET_KEY
    description: Identifier used by GitHub Webhook to make the URL unique.
    required: true
    value: ninja-backend